# 不要修改!
version: 1

# id: `arrow`
arrow:
  namespace: special
  # 可用标签
  # <pierce_level> 穿透等级
  # <fire_ticks> 箭矢本身的着火时间
  # <hit_fire_ticks> 击中实体造成的着火时间
  # <hit_frozen_ticks> 击中实体造成的冰冻时间
  # <glow_ticks> 击中实体造成的发光时间
  tooltip:
    - "<!i><blue>穿透: <pierce_level>"

# id: `attack_speed`
attack_speed:
  namespace: topmost
  tooltip:
    # 可用标签
    # <value> 攻击速度值
    line: "<!i><white>攻击速度<gray>: <value>"

# id: <有效的属性 id>
core/attributes:
  namespace: attribute
  ordinal:
    # 元素排序
    element:
      - neutral
      - fire
      - water
      - wind
      - earth
      - thunder
    # 运算模式排序
    operation:
      - add
      - multiply_base
      - multiply_total

# id: `core/empty`
core/empty:
  namespace: stash
  tooltip:
    - "<dark_gray>[ 空核孔 ]"

# id: `crate`
crate:
  namespace: special
  # 可用标签
  # <id> 盲盒的标识
  # <name> 盲盒的名字
  tooltip: "<!i><gray>盲盒: <yellow><name>"

# id: `custom_name`
custom_name:
  namespace: general
  # 可用标签
  # <value> 物品的 `minecraft:custom_name`
  tooltip: "<value>"

# id: `element`
element:
  namespace: general
  # 可用标签
  # <merged> 多个元素合并后的文本
  # <single> 单个元素
  tooltip:
    merged: "<!i><gray>主要元素: <merged>"
    single: "<single>"
    separator: "<gray>, </gray>"

# id: `enchantments`
enchantments:
  namespace: vanilla

# id: `enchant_slots`
enchant_slots:
  namespace: special
  # 可用标签
  # <used> 使用掉的附魔槽位数量
  # <max_base> 附魔槽位数量的基础上限
  # <max_extra> 附魔槽位数量的额外上限
  # <max_total> 附魔槽位数量的总上限 (base + extra)
  tooltip: "<!i><gray>附魔槽位: <white><used>/<max_base>(+<max_extra>)"

# id: `damage_resistant`
damage_resistant:
  namespace: vanilla
  tooltip: "<!i><blue><value> 伤害免疫"

# id: `food`
food:
  namespace: vanilla
  # 可用标签
  # <nutrition> 食物增加的饥饿值
  # <saturation> 食物增加的饱和度
  # <eat_seconds> 食用所需要的时间
  tooltip:
    - "<!i><blue>饥饿值 +<nutrition>"
    - "<!i><blue>饱和度 +<saturation>"

# id: `item_name`
item_name:
  namespace: general
  # 可用标签
  # <value> 物品的 `minecraft:item_name`
  tooltip: "<value>"

# id: `kizami`
kizami:
  namespace: general
  # 可用标签
  # <merged> 多个铭刻合并后的文本
  # <single> 单个铭刻
  tooltip:
    merged: "<!i><gray>铭刻: <merged>"
    single: "<!i><gray><single>"
    separator: "<gray>, </gray>"

# id: `level`
level:
  namespace: general
  # 可用标签
  # <value> 等级值
  tooltip: "<!i><yellow>lv. <value>"

# id: `lore`
lore:
  namespace: general
  # 可用标签
  # <line> 描述内容
  tooltip:
    line: "<dark_gray><line>"
    header: [ ]
    bottom: [ ]

# id: `core`
core:
  namespace: special

# id: `rarity`
rarity:
  namespace: general
  # 可用标签
  # <rarity_display_name> 稀有度的名字
  # <reforge_mod_count> 被重铸的次数
  # 重铸次数为零的格式
  simple: "<!i><rarity_display_name>"
  # 重铸次数不为零的格式
  complex: "<!i><rarity_display_name><white>[<reforge_mod_count>]"

# id: `entity_bucket_prop`
entity_bucket_prop:
  namespace: special
  # 可用标签
  # <merged> 多个实体类型合并后的文本
  # <single> 单个实体类型
  tooltip:
    merged: "<!i><gray>此桶可捕捉: <merged>"
    single: "<!i><white><single>"
    separator: "<gray>, </gray>"

# id: `entity_bucket_info`
entity_bucket_info:
  namespace: special
  # 内容物描述
  content:
    - "<!i><gray>此桶装有一只<entity_type>"
  # 抽象描述
  abstract:
    ageable:
      - "<!i><gray>已成年: <yellow><is_adult>"
    collar_colorable:
      - "<!i><gray>项圈颜色: <yellow><collar_color>"
    shearable:
      - "<!i><gray>可剪毛: <yellow><ready_to_be_sheared>"
    tameable:
      - "<!i><gray>已驯服"
      - "<!i><gray>从属于: <yellow><owner_name>"
    variable:
      - "<!i><gray>变体: <yellow><variant>"
  # 具体描述
  specific:
    armadillo:
      - "<!i><gray>状态: <yellow><state>"
    bee: [ ]
    camel: [ ]
    cat: [ ]
    chicken: [ ]
    cow: [ ]
    dolphin: [ ]
    donkey: [ ]
    fox: [ ]
    frog: [ ]
    glow_squid: [ ]
    goat:
      - "<!i><gray>有左角: <yellow><has_left_horn>"
      - "<!i><gray>有右角: <yellow><has_right_horn>"
    happy_ghast: [ ]
    hoglin: [ ]
    horse: [ ]
    llama: [ ]
    mooshroom: [ ]
    mule: [ ]
    ocelot:
      - "<!i><gray>信任玩家: <yellow><trusting>"
    panda: [ ]
    parrot: [ ]
    pig: [ ]
    polar_bear: [ ]
    rabbit: [ ]
    sheep: [ ]
    skeleton_horse: [ ]
    sniffer: [ ]
    squid: [ ]
    strider: [ ]
    trader_llama: [ ]
    turtle:
      - "<!i><gray>已怀孕: <yellow><has_egg>"
    wolf: [ ]
    allay:
      - "<!i><gray>左手物品: <yellow><item_in_mainhand>"
      - "<!i><gray>右手物品: <yellow><item_in_offhand>"
    iron_golem:
      - "<!i><gray>人造: <yellow><is_player_created>"
    snow_golem:
      - "<!i><gray>南瓜: <yellow><has_pumpkin>"
    villager:
      - "<!i><gray>等级: <yellow><level>"
      - "<!i><gray>区域: <yellow><region>"
      - "<!i><gray>职业: <yellow><profession>"
    wandering_trader: [ ]
    zombie_villager:
      - "<!i><gray>区域: <yellow><region>"
      - "<!i><gray>职业: <yellow><profession>"

# id: `fuel`
fuel:
  namespace: special
  # 可用标签
  # <burn_time> 燃烧时间 (tick)
  # <consume> 是否会被消耗
  tooltip:
    - "<!i><blue>燃烧时间: <burn_time>t"
    - "<!i><blue>是否消耗: <consume>"

# id: `castable`
castable:
  namespace: special
  # 可用标签
  # <trigger> 触发器描述
  content:
    - "<!i><gray><trigger>释放特殊效果"
  # 触发器描述
  trigger:
    special:
      on_equip: "<!i><light_purple>穿戴时</light_purple>"
      on_unequip: "<!i><light_purple>脱下时</light_purple>"
    generic:
      left_click: "<!i><light_purple>左键</light_purple>"
      right_click: "<!i><light_purple>右键</light_purple>"
    sequence:
      left: "<!i><light_purple>左</light_purple>"
      right: "<!i><light_purple>右</light_purple>"
      separator: ""
    input:
      forward: "<!i><light_purple>前进</light_purple>"
      backward: "<!i><light_purple>后退</light_purple>"
      left: "<!i><light_purple>左移</light_purple>"
      right: "<!i><light_purple>右移</light_purple>"
      jump: "<!i><light_purple>跳跃</light_purple>"
      sneak: "<!i><light_purple>潜行</light_purple>"
      sprint: "<!i><light_purple>冲刺</light_purple>"
