# 不要修改!
version: 1

primary:
  - general:level
  - special:arrow
  - topmost:attack_speed
  - attribute:entity_interaction_range
  - attribute:block_interaction_range
  - attribute:hammer_damage_range
  - attribute:hammer_damage_ratio
  - attribute:sweeping_damage_ratio
  - attribute:attack_knockback
  - attribute:knockback_resistance

  - (fixed:attribute)<st><dark_gray>             </dark_gray></st>
  - attribute:universal_attack_damage
  - attribute:universal_defense
  - attribute:attack_damage
  - attribute:max_health
  - attribute:defense

  - (fixed:attribute)<st><dark_gray>             </dark_gray></st>
  - attribute:universal_defense_penetration
  - attribute:universal_defense_penetration_rate
  - attribute:attack_damage_rate
  - attribute:defense_penetration
  - attribute:defense_penetration_rate
  - attribute:incoming_damage_rate
  - attribute:max_mana
  - attribute:lifesteal
  - attribute:manasteal
  - attribute:max_absorption
  - attribute:attack_effect_chance
  - attribute:critical_strike_chance
  - attribute:critical_strike_power
  - attribute:negative_critical_strike_power
  - attribute:none_critical_strike_power
  - attribute:mana_consumption_rate
  - attribute:mining_efficiency
  - attribute:movement_speed
  - attribute:water_movement_efficiency
  - attribute:safe_fall_distance
  - attribute:scale
  - attribute:step_height
  - attribute:health_regeneration
  - attribute:mana_regeneration
  - (fixed:stash)<st><dark_gray>             </dark_gray></st>
  - stash:core/empty

  - (fixed:vanilla)<st><dark_gray>             </dark_gray></st>
  - vanilla:enchantments
  - special:enchant_slots
  - vanilla:damage_resistant
  - vanilla:food

  - (fixed:special)<st><dark_gray>             </dark_gray></st>
  - special:crate
  - special:core
  - special:entity_bucket_prop
  - special:entity_bucket_info
  - special:fuel
  - special:castable
  - special:network_position
  - special:crate_key_replaced
  - special:random_teleport

  - (fixed:general)<st><dark_gray>             </dark_gray></st>
  - general:kizami
  - general:element
  - general:rarity
  - general:lore

  - (fixed:*)
  - special:effectiveness

# 注意!!! 该节点仅存在于网络物品渲染配置中
#
# 在发送物品网络包到客户端时, 移除以下物品组件
remove_components:
  - minecraft:attribute_modifiers

# 注意!!! 该节点仅存在于本地物品渲染配置中
#
# 在渲染物品时, 隐藏以下物品组件
hidden_components:
  - minecraft:enchantments
