# 不要修改!
version: 1

# Koish 所使用的经济系统
# 可用选项:
#   vanilla: Minecraft 原版经验等级
#   economy: Economy 插件的账户余额
economy_provider: vanilla

# Koish 如何计算玩家的等级
# 可用选项:
#   vanilla: Minecraft 的原版经验等级
#   aura_skills: AuraSkills 插件的技能等级
#   adventure_level: AdventureLevel 插件的冒险等级
player_level_provider: vanilla

# Koish 如何计算玩家的魔法值
# 可用选项:
#   infinity: 无限魔法值
#   aura_skills: AuraSkills 插件的魔法值
player_mana_provider: infinity

# Koish 如何计算物品的附魔槽位的基础容量
# 可用选项:
#   none: 不计算 (相当于原版)
#   prop: 根据物品的 `enchant_slot_base` prop 计算
#   rarity: 根据物品的稀有度 (rarity) 计算
enchant_slot_base_provider: rarity

# Koish 如何获取物品的等级
# 可用选项:
#   data: 从物品堆叠上读取等级
#   type: 从物品类型上读取等级
item_level_provider: data

# Koish 如何获取物品的稀有度
# 可用选项:
#   data: 从物品堆叠上读取稀有度
#   type: 从物品类型上读取稀有度
item_rarity_provider: data

# Koish 如何获取物品的元素
# 可用选项:
#   data: 从物品堆叠上读取元素
#   type: 从物品类型上读取元素
item_element_provider: data

# Koish 如何获取物品的铭刻
# 可用选项:
#   data: 从物品堆叠上读取铭刻
#   type: 从物品类型上读取铭刻
item_kizami_provider: data

# Koish 如何获取物品的核心
# 可用选项:
#   data: 从物品堆叠上读取核心
#   type: 从物品类型上读取核心
item_core_provider: data

# Koish 如何获取物品的核心容器
# 可用选项:
#   data: 从物品堆叠上读取核心容器
#   type: 从物品类型上读取核心容器
item_core_container_provider: data

# 给客户端设置的生命值缩放
clientbound_health_scale: 20.0

# 是否在设置生命值缩放时打印堆栈信息
print_stack_on_set_health_scale: false

# 在发送 ClientboundUpdateAttributesPacket 封包时移除掉以下属性
# 目前仅用于配合伤害系统来“移除” ARMOR 和 ARMOR_TOUGHNESS 这两属性
# 实际生产环境中此功能的作用: 不再需要使用特制的资源包隐藏掉护甲 HUD
remove_attributes_on_clientbound_update_attributes_packet:
  - minecraft:armor
  - minecraft:armor_toughness

# 在发送 ClientboundSetEntityDataPacket 封包时移除掉 ABSORPTION 数据
remove_absorption_on_clientbound_set_entity_data_packet: true

# 关于调试模式
debug:
  # 显示攻击碰撞箱
  attack_hitbox: false
  # 调试模式信息记录控制
  logging:
    # 记录 Initializer
    initializer: false
    # 记录 Reloader
    reloader: false
    # 记录 DamageListener
    damage: false
    # 记录 Registry
    registry: false
    # 记录 ItemStackRenderer
    renderer: false
