# 不要修改!
version: 1

# 消息队列相关配置
# 部分功能需要该配置正确才能正常工作
messaging:
  # 是否启用消息队列
  enabled: false
  # 使用的消息队列: NATS, RABBITMQ, REDIS
  broker_type: NATS
  # NATS
  nats:
    host: "localhost"
    port: 4222
    credentials_file: ""
  # RabbitMQ
  rabbitmq:
    host: "localhost"
    port: 5672
    vhost: "/"
    user: "user"
    pass: "pass"
  # Redis
  redis:
    host: "localhost"
    port: 6379
    pass: ""

# Koish 所使用的经济系统
# 可用选项:
#   vanilla: Minecraft 原版经验等级
#   economy: Economy 插件的账户余额
economy_provider: vanilla

# Koish 如何计算玩家的等级
# 可用选项:
#   vanilla: Minecraft 的原版经验等级
#   aura_skills: AuraSkills 插件的技能等级
#   adventure: AdventureLevel 插件的冒险等级
player_level_provider: vanilla

# Koish 如何计算玩家的魔法值
# 可用选项:
#   infinity: 无限魔法值
#   aura_skills: AuraSkills 插件的魔法值
player_mana_provider: infinity

# 只有物品的所有者可以拾起死亡掉落的物品
only_owner_can_pickup_death_drops: false

# 要求玩家必须在潜行状态下才能够破坏盔甲架
require_sneaking_to_break_armor_stand: false

# 世界时间控制器的全局最小使用间隔 (刻)
world_time_control_use_interval_ticks: 12000

# 世界天气控制器的全局最小使用间隔 (刻)
world_weather_control_use_interval_ticks: 12000

# Koish 如何计算物品的附魔槽位的基础容量
# 可用选项:
#   none: 不计算 (相当于原版)
#   prop: 根据物品的 `enchant_slot_base` prop 计算
#   rarity: 根据物品的稀有度 (rarity) 计算
enchant_slot_base_provider: rarity

# Koish 如何获取物品的等级
# 可用选项:
#   data: 从物品堆叠上读取等级
#   type: 从物品类型上读取等级
item_level_provider: data

# Koish 如何获取物品的稀有度
# 可用选项:
#   data: 从物品堆叠上读取稀有度
#   type: 从物品类型上读取稀有度
item_rarity_provider: data

# Koish 如何获取物品的元素
# 可用选项:
#   data: 从物品堆叠上读取元素
#   type: 从物品类型上读取元素
item_element_provider: data

# Koish 如何获取物品的铭刻
# 可用选项:
#   data: 从物品堆叠上读取铭刻
#   type: 从物品类型上读取铭刻
item_kizami_provider: data

# Koish 如何获取物品的核心
# 可用选项:
#   data: 从物品堆叠上读取核心
#   type: 从物品类型上读取核心
item_core_provider: data

# Koish 如何获取物品的核心容器
# 可用选项:
#   data: 从物品堆叠上读取核心容器
#   type: 从物品类型上读取核心容器
item_core_container_provider: data

# 禁止玩家在以下世界中与村民进行交易
disable_villager_trade_in_worlds:
  - koish:eden
  - koish:dune
  - koish:hollow

# 映射: 维度技术名字 -> 维度友好名字
# 目前用于配置 %koish_current_dimension% 占位符的输出
dimension_key_mappings:
  minecraft:overworld: 主世界
  minecraft:nether: 下界
  minecraft:end: 末地

# 可以点亮下界传送门的维度名字列表
nether_portal_functional_dimensions:
  - koish:hollow

# 玩家明确进入服务器时, 修改其出现在世界里的位置坐标
teleport_on_join_explicit_server:
  # 是否启用该功能
  enabled: false
  # 执行传送的条件
  conditions:
    - { type: server_group, group: xmine }
  # 传送到的位置列表
  locations:
    - { world: koish:eden, x: 2500, y: 128, z: 2500 }
    - { world: koish:eden, x: 2500, y: 128, z: -2500 }
    - { world: koish:eden, x: -2500, y: 128, z: 2500 }
    - { world: koish:eden, x: -2500, y: 128, z: -2500 }
  # 传送后应用的效果
  effects:
    - { type: minecraft:slow_falling, duration: 200, amplifier: 1 }

# 鞘翅扩展
elytra_extras:
  # 是否启用该功能
  enabled: false
  # 滑翔时每秒消耗的魔法值
  glide_drain_per_second: 1.0
  # 进入滑翔时消耗的魔法值
  enter_glide_mana_cost: 2.0
  # 使用烟花时消耗的魔法值
  rocket_boost_mana_cost: 10.0

# 在发送 ClientboundUpdateAttributesPacket 封包时移除掉以下属性
# 目前仅用于配合伤害系统来“移除” ARMOR 和 ARMOR_TOUGHNESS 这两属性
# 此功能可以带来几个好处:
# - 不再需要手动移除掉物品自带的 minecraft:attribute_modifiers 组件
# - 不再需要使用特制的资源包隐藏掉护甲 HUD
remove_attributes_on_clientbound_update_attributes_packet:
  - minecraft:armor
  - minecraft:armor_toughness

# 在发送 ClientboundSetEntityDataPacket 封包时移除掉 ABSORPTION 数据
remove_absorption_on_clientbound_set_entity_data_packet: true

# 关于调试模式
debug:
  # 显示攻击碰撞箱
  attack_hitbox: false
  # 调试模式信息记录控制
  logging:
    # 记录 Initializer
    initializer: false
    # 记录 Reloader
    reloader: false
    # 记录 DamageListener
    damage: false
    # 记录 Registry
    registry: false
    # 记录 ItemStackRenderer
    renderer: false
