# 有序配方, 参考: https://minecraft.wiki/w/Recipe#crafting_shaped
type: shaped

# 解锁该配方时, 是否弹出提示
# 仅有序合成配方有这个选项
show_notification: true

# 合成方格中物品要摆放成的合成图案
# 其中的每个字符串代表合成方格中的一横行
pattern:
  - XAX
  - ABA
  - XAX

# 一个映射表, 用于将字符与合成材料物品建立关联
# 字符将用于在上面的 pattern 中指定合成的图案
ingredients:
  A:
    - minecraft:gold_block
    - minecraft:diamond_block
  B: minecraft:apple

# 该配方输出的单个物品堆叠
result:
  item: minecraft:enchanted_golden_apple
  amount: 1