# 锻造纹饰配方, 参考: https://minecraft.wiki/w/Recipe#smithing_trim
type: smithing_trim

# 表示要被添加纹饰的基础物品, 一般为盔甲
base: example/bronze_helmet

# 表示要添加到基础物品上的盔甲纹饰图案
pattern: minecraft:silence

# 表示为基础物品添加纹饰时所需的额外材料
# 将由物品的 provides_trim_material 物品堆叠组件确定添加到基础物品上的盔甲纹饰材料
addition:
  - minecraft:amethyst_shard
  - minecraft:copper_ingot
  - minecraft:diamond
  - minecraft:emerald
  - minecraft:gold_ingot
  - minecraft:iron_ingot
  - minecraft:lapis_lazuli
  - minecraft:netherite_ingot
  - minecraft:quartz
  - minecraft:redstone

# 表示为基础物品添加纹饰时所需的模板物品
template: minecraft:silence_armor_trim_smithing_template